name: Submit/Update a System Template
description: Submit/Update a System Template
title: "[Template]: "
labels: ["template"]
projects: []
assignees:
  - EddieDover
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this System Template form!
  - type: input
    id: system
    attributes:
      label: What system is the new template for?
      description: Please list both the standard system name and the system short name.
      placeholder: DND5E "dnd5e", The Walking Dead Universe RPG "twdu", etc
    validations:
      required: true
  - type: textarea
    id: system-json
    attributes:
      label: Your system template code
      description: Just copy and paste in your template code
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Screenshot"
  - type: markdown:
    attributes: "Please include a screenshot of your template, open in the party sheet window"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or discord_username
    validations:
      required: false
